//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MireWpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MireWpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string Dir1 {
            get {
                return ResourceManager.GetString("Dir1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAD.
        /// </summary>
        public static string Dir2 {
            get {
                return ResourceManager.GetString("Dir2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Dir3 {
            get {
                return ResourceManager.GetString("Dir3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string DirTitle {
            get {
                return ResourceManager.GetString("DirTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spindle.
        /// </summary>
        public static string ForceUk {
            get {
                return ResourceManager.GetString("ForceUk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHEEL NAME.
        /// </summary>
        public static string FW1 {
            get {
                return ResourceManager.GetString("FW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering.
        /// </summary>
        public static string FW10 {
            get {
                return ResourceManager.GetString("FW10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIKE.
        /// </summary>
        public static string FW11 {
            get {
                return ResourceManager.GetString("FW11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        public static string FW12 {
            get {
                return ResourceManager.GetString("FW12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair ID.
        /// </summary>
        public static string FW13 {
            get {
                return ResourceManager.GetString("FW13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERFORMANCE.
        /// </summary>
        public static string FW14 {
            get {
                return ResourceManager.GetString("FW14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEOMETRY.
        /// </summary>
        public static string FW15 {
            get {
                return ResourceManager.GetString("FW15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIDE TO SIDE.
        /// </summary>
        public static string FW16 {
            get {
                return ResourceManager.GetString("FW16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP AND DOWN.
        /// </summary>
        public static string FW17 {
            get {
                return ResourceManager.GetString("FW17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFSET.
        /// </summary>
        public static string FW18 {
            get {
                return ResourceManager.GetString("FW18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPOKE TENSION.
        /// </summary>
        public static string FW19 {
            get {
                return ResourceManager.GetString("FW19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUB.
        /// </summary>
        public static string FW2 {
            get {
                return ResourceManager.GetString("FW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVERAGE ALL SPOKES.
        /// </summary>
        public static string FW20 {
            get {
                return ResourceManager.GetString("FW20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EACH SPOKE.
        /// </summary>
        public static string FW21 {
            get {
                return ResourceManager.GetString("FW21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEFT.
        /// </summary>
        public static string FW22 {
            get {
                return ResourceManager.GetString("FW22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIGHT.
        /// </summary>
        public static string FW23 {
            get {
                return ResourceManager.GetString("FW23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX.
        /// </summary>
        public static string FW24 {
            get {
                return ResourceManager.GetString("FW24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN.
        /// </summary>
        public static string FW25 {
            get {
                return ResourceManager.GetString("FW25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STABILIZATION.
        /// </summary>
        public static string FW26 {
            get {
                return ResourceManager.GetString("FW26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of hit / kg.
        /// </summary>
        public static string FW27 {
            get {
                return ResourceManager.GetString("FW27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string FW28 {
            get {
                return ResourceManager.GetString("FW28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nb hit/Nb turn.
        /// </summary>
        public static string FW29 {
            get {
                return ResourceManager.GetString("FW29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string FW3 {
            get {
                return ResourceManager.GetString("FW3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string FW4 {
            get {
                return ResourceManager.GetString("FW4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIM.
        /// </summary>
        public static string FW5 {
            get {
                return ResourceManager.GetString("FW5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perimeter.
        /// </summary>
        public static string FW6 {
            get {
                return ResourceManager.GetString("FW6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to control.
        /// </summary>
        public static string FW7c {
            get {
                return ResourceManager.GetString("FW7c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry.
        /// </summary>
        public static string FW7s {
            get {
                return ResourceManager.GetString("FW7s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPOKE ANALYSER.
        /// </summary>
        public static string FW8 {
            get {
                return ResourceManager.GetString("FW8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string FW9 {
            get {
                return ResourceManager.GetString("FW9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string LogTitle {
            get {
                return ResourceManager.GetString("LogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainWindow.
        /// </summary>
        public static string MainWindows {
            get {
                return ResourceManager.GetString("MainWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string MesFr {
            get {
                return ResourceManager.GetString("MesFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inch.
        /// </summary>
        public static string MesUk {
            get {
                return ResourceManager.GetString("MesUk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        public static string PoidsFr {
            get {
                return ResourceManager.GetString("PoidsFr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb.
        /// </summary>
        public static string PoidsUk {
            get {
                return ResourceManager.GetString("PoidsUk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADJUST HUB WIDTH.
        /// </summary>
        public static string PopUpTitle1 {
            get {
                return ResourceManager.GetString("PopUpTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET PERIMETER.
        /// </summary>
        public static string PopUpTitle2 {
            get {
                return ResourceManager.GetString("PopUpTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYMMETRY CONTROL.
        /// </summary>
        public static string PopUpTitle3 {
            get {
                return ResourceManager.GetString("PopUpTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHEEL INFO.
        /// </summary>
        public static string PopUpTitleID {
            get {
                return ResourceManager.GetString("PopUpTitleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Parameters.
        /// </summary>
        public static string PopUpTitleParams {
            get {
                return ResourceManager.GetString("PopUpTitleParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string PopUpTitlePass {
            get {
                return ResourceManager.GetString("PopUpTitlePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string PopUpTitleSave {
            get {
                return ResourceManager.GetString("PopUpTitleSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string PopUpTitleShut {
            get {
                return ResourceManager.GetString("PopUpTitleShut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabilisation Scale.
        /// </summary>
        public static string PopUpTitleStab {
            get {
                return ResourceManager.GetString("PopUpTitleStab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP 1. GO IN HOME POSITION.
        /// </summary>
        public static string PopUpTxt21 {
            get {
                return ResourceManager.GetString("PopUpTxt21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Rotate wheel to valve hole).
        /// </summary>
        public static string PopUpTxt22 {
            get {
                return ResourceManager.GetString("PopUpTxt22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP 2. PRESS Acquisition Button to Reset Value.
        /// </summary>
        public static string PopUpTxt23 {
            get {
                return ResourceManager.GetString("PopUpTxt23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP 3. Manually rotate wheel up to final position.
        /// </summary>
        public static string PopUpTxt24 {
            get {
                return ResourceManager.GetString("PopUpTxt24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP 1. LOAD A WHEEL.
        /// </summary>
        public static string PopUpTxt31 {
            get {
                return ResourceManager.GetString("PopUpTxt31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP 2.  UNLOAD THE WHEEL, FLIP IT,.
        /// </summary>
        public static string PopUpTxt32 {
            get {
                return ResourceManager.GetString("PopUpTxt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAD WHEEL, ROTATE WHEEL ENTIRELY.
        /// </summary>
        public static string PopUpTxt33 {
            get {
                return ResourceManager.GetString("PopUpTxt33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP 3. SYMMETRY ERROR.
        /// </summary>
        public static string PopUpTxt34 {
            get {
                return ResourceManager.GetString("PopUpTxt34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP 4. SYMMETRY CORRECTION.
        /// </summary>
        public static string PopUpTxt35 {
            get {
                return ResourceManager.GetString("PopUpTxt35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter ID :.
        /// </summary>
        public static string PopUpTxtID {
            get {
                return ResourceManager.GetString("PopUpTxtID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Admin Password:.
        /// </summary>
        public static string PopUpTxtPass1 {
            get {
                return ResourceManager.GetString("PopUpTxtPass1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password!.
        /// </summary>
        public static string PopUpTxtPass2 {
            get {
                return ResourceManager.GetString("PopUpTxtPass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes ?.
        /// </summary>
        public static string PopUpTxtSave1 {
            get {
                return ResourceManager.GetString("PopUpTxtSave1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwriting wheel number :.
        /// </summary>
        public static string PopUpTxtSave2 {
            get {
                return ResourceManager.GetString("PopUpTxtSave2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown System ?.
        /// </summary>
        public static string PopUpTxtShut {
            get {
                return ResourceManager.GetString("PopUpTxtShut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPOKE NAME.
        /// </summary>
        public static string SP1 {
            get {
                return ResourceManager.GetString("SP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CALIBRATION.
        /// </summary>
        public static string SP2 {
            get {
                return ResourceManager.GetString("SP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCURACY.
        /// </summary>
        public static string SP3 {
            get {
                return ResourceManager.GetString("SP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE.
        /// </summary>
        public static string SP4 {
            get {
                return ResourceManager.GetString("SP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALIDITY.
        /// </summary>
        public static string SP5 {
            get {
                return ResourceManager.GetString("SP5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAUGE.
        /// </summary>
        public static string SP6 {
            get {
                return ResourceManager.GetString("SP6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPARATOR IN MM.
        /// </summary>
        public static string SP7 {
            get {
                return ResourceManager.GetString("SP7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPOKE.
        /// </summary>
        public static string SPTitle {
            get {
                return ResourceManager.GetString("SPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcul Offset.
        /// </summary>
        public static string USC1 {
            get {
                return ResourceManager.GetString("USC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jointure Invisible.
        /// </summary>
        public static string USC2 {
            get {
                return ResourceManager.GetString("USC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase Scratchs.
        /// </summary>
        public static string USC3 {
            get {
                return ResourceManager.GetString("USC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Refresh.
        /// </summary>
        public static string USC4 {
            get {
                return ResourceManager.GetString("USC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USC5 {
            get {
                return ResourceManager.GetString("USC5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USC6 {
            get {
                return ResourceManager.GetString("USC6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USC7 {
            get {
                return ResourceManager.GetString("USC7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USCLabel1 {
            get {
                return ResourceManager.GetString("USCLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USCLabel2 {
            get {
                return ResourceManager.GetString("USCLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USCLabel3 {
            get {
                return ResourceManager.GetString("USCLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USCLabel4 {
            get {
                return ResourceManager.GetString("USCLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computation.
        /// </summary>
        public static string USCTitle {
            get {
                return ResourceManager.GetString("USCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Zoom.
        /// </summary>
        public static string USD1 {
            get {
                return ResourceManager.GetString("USD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Fit.
        /// </summary>
        public static string USD2 {
            get {
                return ResourceManager.GetString("USD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string USD3B {
            get {
                return ResourceManager.GetString("USD3B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar.
        /// </summary>
        public static string USD3R {
            get {
                return ResourceManager.GetString("USD3R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY.
        /// </summary>
        public static string USD3XY {
            get {
                return ResourceManager.GetString("USD3XY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USD4 {
            get {
                return ResourceManager.GetString("USD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USD5 {
            get {
                return ResourceManager.GetString("USD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min-Max.
        /// </summary>
        public static string USD6 {
            get {
                return ResourceManager.GetString("USD6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string USD7 {
            get {
                return ResourceManager.GetString("USD7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string USDLabel1 {
            get {
                return ResourceManager.GetString("USDLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Time.
        /// </summary>
        public static string USDLabel2 {
            get {
                return ResourceManager.GetString("USDLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tension Array.
        /// </summary>
        public static string USDLabel3 {
            get {
                return ResourceManager.GetString("USDLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string USDLabel4 {
            get {
                return ResourceManager.GetString("USDLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string USDTitle {
            get {
                return ResourceManager.GetString("USDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USG1 {
            get {
                return ResourceManager.GetString("USG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USG2 {
            get {
                return ResourceManager.GetString("USG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USG3 {
            get {
                return ResourceManager.GetString("USG3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USG4 {
            get {
                return ResourceManager.GetString("USG4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USG5 {
            get {
                return ResourceManager.GetString("USG5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USG6 {
            get {
                return ResourceManager.GetString("USG6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USG7 {
            get {
                return ResourceManager.GetString("USG7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string USGLabel1 {
            get {
                return ResourceManager.GetString("USGLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string USGLabel2 {
            get {
                return ResourceManager.GetString("USGLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USGLabel3 {
            get {
                return ResourceManager.GetString("USGLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USGLabel4 {
            get {
                return ResourceManager.GetString("USGLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic.
        /// </summary>
        public static string USGTitle {
            get {
                return ResourceManager.GetString("USGTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string USMTitle {
            get {
                return ResourceManager.GetString("USMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string USP1 {
            get {
                return ResourceManager.GetString("USP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celebrate.
        /// </summary>
        public static string USP2 {
            get {
                return ResourceManager.GetString("USP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pedal (Auto).
        /// </summary>
        public static string USP3 {
            get {
                return ResourceManager.GetString("USP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd / Even.
        /// </summary>
        public static string USP4 {
            get {
                return ResourceManager.GetString("USP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USP5 {
            get {
                return ResourceManager.GetString("USP5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USP6 {
            get {
                return ResourceManager.GetString("USP6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USP7 {
            get {
                return ResourceManager.GetString("USP7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spoke analyser.
        /// </summary>
        public static string USPLabel1 {
            get {
                return ResourceManager.GetString("USPLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USPLabel2 {
            get {
                return ResourceManager.GetString("USPLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USPLabel3 {
            get {
                return ResourceManager.GetString("USPLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USPLabel4 {
            get {
                return ResourceManager.GetString("USPLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Print Wheel Ok.
        /// </summary>
        public static string USPr1 {
            get {
                return ResourceManager.GetString("USPr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string USPr2 {
            get {
                return ResourceManager.GetString("USPr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string USPr3 {
            get {
                return ResourceManager.GetString("USPr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date / Hour.
        /// </summary>
        public static string USPr4 {
            get {
                return ResourceManager.GetString("USPr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final value.
        /// </summary>
        public static string USPr5 {
            get {
                return ResourceManager.GetString("USPr5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torque Min.
        /// </summary>
        public static string USPr6 {
            get {
                return ResourceManager.GetString("USPr6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torque Max.
        /// </summary>
        public static string USPr7 {
            get {
                return ResourceManager.GetString("USPr7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Manual.
        /// </summary>
        public static string USPr8 {
            get {
                return ResourceManager.GetString("USPr8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USPrLabel1 {
            get {
                return ResourceManager.GetString("USPrLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USPrLabel2 {
            get {
                return ResourceManager.GetString("USPrLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USPrLabel3 {
            get {
                return ResourceManager.GetString("USPrLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string USPrLabel4 {
            get {
                return ResourceManager.GetString("USPrLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string USPrTitle {
            get {
                return ResourceManager.GetString("USPrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string USPTitle {
            get {
                return ResourceManager.GetString("USPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string USTitle {
            get {
                return ResourceManager.GetString("USTitle", resourceCulture);
            }
        }
    }
}
